language: csharp
mono: latest
dotnet: 3.1.302
before_install:
 - sudo apt-get update
install:
 - dotnet restore
script:
 - dotnet build ./MintPlayer.IconUtils/MintPlayer.IconUtils.csproj --configuration Release
sudo: required